name: '[PSH] Quality Engineering'

on:
  push:
    branches:
      - master
      - main

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v2
    with:
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_affirm-api
      dotnetSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
